add firefox tests

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -38,7 +38,7 @@ jobs:
       fail-fast: false
       matrix:
         # run copies of the current job in parallel
-        containers: [1, 2, 3, 4, 5]
+        containers: [1, 2]
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -47,7 +47,7 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           name: build
-          path: build
+          path: dist
 
       - name: Start JSON Server
         run: npx json-server db.json --port=3000 &
@@ -66,6 +66,54 @@ jobs:
           record: true
           parallel: true
           group: "UI - Chrome"
+          spec: cypress/tests/ui/*
+          config-file: cypress.config.ts
+        env:
+          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
+          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          # DEBUG: "cypress:server:args"
+
+  ui-firefox-tests:
+    timeout-minutes: 15
+    runs-on: ubuntu-latest
+    container:
+      image: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
+      options: --user 1001
+    needs: install
+    strategy:
+      # when one test fails, DO NOT cancel the other
+      fail-fast: false
+      matrix:
+        # run copies of the current job in parallel
+        containers: [1, 2]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Download the build folders
+        uses: actions/download-artifact@v4
+        with:
+          name: build
+          path: dist
+
+      - name: Start JSON Server
+        run: npx json-server db.json --port=3000 &
+        
+      - name: Wait for JSON Server to start
+        run: |
+          while ! nc -z localhost 3000; do sleep 1; done
+
+      - name: "UI Tests - Firefox"
+        uses: cypress-io/github-action@v6
+        with:
+          start: npm start:ci --port=4200
+          wait-on: "http://localhost:4200"
+          wait-on-timeout: 120
+          browser: chrome
+          record: true
+          parallel: true
+          group: "UI - Firefox"
           spec: cypress/tests/ui/*
           config-file: cypress.config.ts
         env:
